export const TYPES = {
    CONNECTION_FACTORY: Symbol.for("CONNECTION_FACTORY"),
    POSTGRES_DRIVER: Symbol.for("POSTGRES_DRIVER"),
    USER_REPOSITORY: Symbol.for('USER_REPOSITORY'),
    USER_CONTROLLER: Symbol.for('USER_CONTROLLER'),
    USER_VIEW: Symbol.for('USER_VIEW'),
    JWT_SECRECT_KEY: Symbol.for('JWT_SECRECT_KEY'),
    JWT_DURATION_S: Symbol.for('JWT_DURATION_S'),
    JWT_AUTHENTICATOR: Symbol.for('JWT_AUTHENTICATOR'),
    USER_AUTHORIZER: Symbol.for('USER_AUTHORIZER'),
    ADMIN_AUTHORIZER: Symbol.for('ADMIN_AUTHORIZER'),
    IMAGE_REPOSITORY: Symbol.for("IMAGE_REPOSITORY"),
    BINARY_REPOSITORY: Symbol.for("BINARY_REPOSITORY"),
    PRODUCT_PRICE_REPOSITORY: Symbol.for("PRODUCT_PRICE_REPOSITORY"),
    PRODUCT_REPOSITORY: Symbol.for("PRODUCT_REPOSITORY"),
    PRODUCT_IMAGE_CONTROLLER: Symbol.for("PRODUCT_IMAGE_CONTROLLER"),
    PRODUCT_CONTROLLER: Symbol.for("PRODUCT_CONTROLLER"),
    PRODUCT_VIEW: Symbol.for("PRODUCT_VIEW"),
    IMAGE_VIEW: Symbol.for("IMAGE_VIEW"),
    PRODUCT_CATEGORY_REPOSITORY: Symbol.for("PRODUCT_CATEGORY_REPOSITORY"),
    PRODUCT_CATEGORY_CONTROLLER: Symbol.for("PRODUCT_CATEGORY_CONTROLLER"),
    PRODUCT_CATEGORY_VIEW: Symbol.for("PRODUCT_CATEGORY_VIEW"),
    AREA_TRANSPORT_FEE_REPOSITORY: Symbol.for("AREA_TRANSPORT_FEE_REPOSITORY"),
    TRANSPORT_FEE_CONTROLLER: Symbol.for("TRANSPORT_FEE_CONTROLLER"),
    TRANSPORT_FEE_VIEW: Symbol.for("TRANSPORT_FEE_VIEW"),
    END_USER_PRODUCT_VIEW: Symbol.for('END_USER_PRODUCT_VIEW'),
    END_USER_PRODUCT_CATEGORY_VIEW: Symbol.for('END_USER_PRODUCT_CATEGORY_VIEW'),
    GEOCODER_SERVICE: Symbol.for('GEOCODER_SERVICE'),
    END_USER_GEOCODER_CONTROLLER: Symbol.for('END_USER_GEOCODER_CONTROLLER'),
    END_USER_GEOCODER_VIEW: Symbol.for('END_USER_GEOCODER_VIEW'),
    
    GEOCODER_CONTROLLER: Symbol.for('GEOCODER_CONTROLLER'),

    GOOGLE_GEOCODER_OPTION: Symbol.for('GOOGLE_GEOCODER_OPTION'),
    GOOGLE_GEOCODER_API_KEY: Symbol.for('GOOGLE_GEOCODER_API_KEY'),

    END_USER_TRANSPORT_FEE_CONTROLLER: Symbol.for('END_USER_TRANSPORT_FEE_CONTROLLER'),
    END_USER_TRANSPORT_FEE_VIEW: Symbol.for('END_USER_TRANSPORT_FEE_VIEW'),

    ORDER_REPOSITORY: Symbol.for('ORDER_REPOSITORY'),
    ADDRESS_REPOSITORY: Symbol.for('ADDRESS_REPOSITORY'),
    CUSTOMER_CONTACT_REPOSITORY: Symbol.for('CUSTOMER_CONTACT_REPOSITORY'),

    END_USER_ORDER_CONTROLLER: Symbol.for('END_USER_ORDER_CONTROLLER'),
    END_USER_ORDER_VIEW: Symbol.for('END_USER_ORDER_VIEW'),

    END_USER_PRODUCT_CONTROLLER: Symbol.for('END_USER_PRODUCT_CONTROLLER'),

    END_USER_ADDRESS_CONTROLLER: Symbol.for('END_USER_ADDRESS_CONTROLLER'),

    EMAIL_SERVICE: Symbol.for('EMAIL_SERVICE'),
    ADMIN_EMAIL: Symbol.for('ADMIN_EMAIL'),

    ADMIN_ORDER_CONTROLLER: Symbol.for('ADMIN_ORDER_CONTROLLER'),
    ADMIN_ORDER_VIEW: Symbol.for('ADMIN_ORDER_VIEW'),

    GOOGLE_CLOUD_STORAGE: Symbol.for('GOOGLE_CLOUD_STORAGE'),
    GOOGLE_CLOUD_STORAGE_BUCKET_NAME: Symbol.for('GOOGLE_CLOUD_STORAGE_BUCKET_NAME'),

    SEND_GRID_API_KEY: Symbol.for('SEND_GRID_API_KEY'),
    SEND_GRID_SENDER_EMAIL: Symbol.for('SEND_GRID_SENDER_EMAIL'),

    PRICE_REQUEST_REPOSITORY: Symbol.for('PRICE_REQUEST_REPOSITORY'),

    END_USER_PRICE_REQUEST_CONTROLLER: Symbol.for('END_USER_PRICE_REQUEST_CONTROLLER'),
    END_USER_PRICE_REQUEST_VIEW: Symbol.for('END_USER_PRICE_REQUEST_VIEW'),
}